version: '3.8'

services:
  app:
    image: node:22-alpine
    container_name: nestjs-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    depends_on:
      - firebase

  firebase:
    image: bitnami/firebase-adminsdk
    container_name: firebase
    environment:
      - FIREBASE_PROJECT_ID=your_project_id
      - FIREBASE_CLIENT_EMAIL=your_client_email
      - FIREBASE_PRIVATE_KEY=your_private_key
    volumes:
      - ./path/to/firebase-adminsdk.json:/firebase-adminsdk.json